global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 'app:30080'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [ __meta_kubernetes_pod_name ]
        action: replace
        target_label: pod

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']



