name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy_minikube:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.28.0' # Specify a specific version

      - name: Install minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start minikube
        run: minikube start

      - name: Apply deployment to minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl rollout status deployment/ # Replace with your deployment name
          kubectl get service app # Replace with your service name to confirm it exists

